### ISSUE TITLE
Multiple Lines in Header?

### ISSUE THREAD

**Issue by bodagetta** [react-csv/react-csv#125]
Is it possible to have multiple lines in the header? I'd like to be able to include to text before the label/key header row.

**Comment by bodagetta** [comment]
I find it useful to include lines with comments about the data before the header row. It doesn't look nice to have these comments appear after the header row. An example is below.

```
This is data for sensor 01124343
Data exported 11/27/2018
Headerfield1   Headerfield2   Headerfield3
100.4               143.4               323.4


```

**Comment by mccabemj** [comment]
If someone could come up with an interesting, neat way of doing this, we can take a look. Sounds like it could help some people in an edge case.

**Comment by mriccid** [comment]
I would argue against this, because having multiple lines before the headers line would cause the output to no longer be a valid CSV file. It's similar to people asking for two CSV documents in one file with different headers. Changes like this are undesirable in my opinion as they steer this component away from what it is meant to do, and what it is meant to do well: provide React components that allow users to download CSV files.

**Comment by mccabemj** [comment]
@mriccid makes a valid point. The RFC 4180 standard says `An optional header` (plural), so I'd agree we should keep to the standard

**Comment by Liaomessi** [comment]
Is there some solutions to solve multiple lines header? please show me the link.

**Comment by ayub-786** [comment]
> 

i m not understand by your ans how will you add multi header in excel sheet using react-csv

**Comment by koji-koji** [comment]
@ayub-786 
I think you can set multi-line headers by referring to this issue.
#275
