### ISSUE TITLE
How to display correct too long number in file

### ISSUE THREAD

**Issue by lenLch** [react-csv/react-csv#198]
If the number value is too long, it will display into e....
how to configure cvslink to display the correct value.

**Comment by mvandergrift** [comment]
If you're talking about Excel, you need to import the value as a literal (string) instead of a number. There are a few ways to do this - none of them good. I've always ended up appending a tab character to the value I'm exporting as it doesn't interfere with other programs that may need the CSV file outside of Excel. You do need to ensure the tab character is enclosed, with the numeric value, by quotes. Something like this:

"string value", "123", "1239501018291.19581\t"

You may need to convert the column back into a numeric form if you're planning on performing calculations on it, but for simple display purposes this works.
