### ISSUE TITLE
Columns appearing in different orders

### ISSUE THREAD

**Issue by Shelby-Jean** [react-csv/react-csv#297]
When exported, sometimes columns appear in different orders and I'm unsure why. Has anyone else encountered this or know a fix? TIA!

![image](https://user-images.githubusercontent.com/62919411/135910990-e481eb67-e6a6-4136-9343-dbce3493b232.png)
![image](https://user-images.githubusercontent.com/62919411/135911037-b355a2d6-bef0-4721-b3cc-80d82920295f.png)

**Comment by thatPranav** [comment]
Send sample data to replicate.

**Comment by marrouchi** [comment]
@Shelby-Jean Are you using JSON data as input ? If it's the case, I think that the attribute of some objects may be in the wrong place or undefined. I think it's safer to provider the "headers" prop in order to make sure columns appear in the right order. Like @thatPranav a sample data maybe helpful to identify the issue.

**Comment by abdennour** [comment]
@marrouchi  comment is fair enough
