### ISSUE TITLE
React-CSV stops App from rendering if there are undefined indices in the data provided

### ISSUE THREAD

**Issue by NandoTheessen** [react-csv/react-csv#80]
# Expected Behavior
Provide a DL- Link that serves the CSV export, return empty lines for undefined / null indices

# Current Behavior
If there are undefined / null indices in the array passed to CSVLink it stops the app from rendering

# Possible Solution
A single piece of logic inserted into the "row".map method (lib/core.js:60) that returns null when encountering an undefined / null index

# Steps to Reproduce
Pass an array that has an index that is undefined or null to react-csv

# Context (Environment)
React application

# Detailed Description
Without the below addition in line 60 - 62 the app can not compile.

![screenshot from 2018-05-24 23-04-23](https://user-images.githubusercontent.com/37676385/40513703-d5fb7b04-5fa6-11e8-9020-240a413416b3.jpg)

I can open a PR to add the necessary logic if you guys want. Thanks for a very easy to handle package :+1:

**Comment by mccabemj** [comment]
@NandoTheessen Can you give me some example source data for me to recreate?

**Comment by NandoTheessen** [comment]
Any array with an index that is either null or undefined.
As you are using .map on all of them that throws an error and leads to the app crashing

**Comment by mriccid** [comment]
I'm not sure if there's been a conversation before about how the component should handle `null` rows so maybe that should happen, but for now can you use `Array.prototype.filter` to remove the empty row? 

If you want to render a `null` row, convert it to a non-null array of undefined or null values, e.g.
```
const data = [
	[1, 2, 3, 4],
	[null, null, null, null],
	[5, 6, 7, 8]
]
```

**Comment by mccabemj** [comment]
@NandoTheessen There may need to be some discussion around how to handle null/undefined values (I.e do we omit them, or have them as blank lines) but I definitely agree there needs to be something that handles them instead of throwing an error.

I'd suggest `if (row == null)` which would check for null and undefined. 

I don't see a need to give the user an option what to do with null values, so I suggest we do as above. Return null when found, which would give a blank line. If the user didn't want a blank like, then they should filter the data first. We can only work with the data provided, so the inclusion of an index should output a line regardless IMO.

@NandoTheessen want to do a PR for this? Please include some tests for data with null/undefined values.

**Comment by NandoTheessen** [comment]
@mccabemj 
Sounds good, I'll make a PR this weekend 👍
